### ISSUE TITLE
Signal viewer crosshair

### ISSUE THREAD

**Issue by AD-256** [ctigaret/scipyen#72]
- The bounds of the cross-hair cursor aren't limited to the bounds of the viewport but instead seem to be limited to the bounds of the size of the window outside of full-screen

- It leaves glitchy duplicates of itself when leaving the bounds

- The individual axis of the cross-hair can split apart when the opposite axis has been restricted by the first issue

 
![image](https://user-images.githubusercontent.com/128634438/233065474-981b58f9-5598-4e3b-84e6-35ceedbca566.png)
Here you can see the y axis has detached from the x axis because of the bounds error and the glitchy duplicates

![image](https://user-images.githubusercontent.com/128634438/233068237-8e07a0a1-dcbe-4610-9fa0-857bfcc7d342.png)
here the y axis has been allowed to deviate from the bottom of the viewport

**Comment by ctigaret** [comment]
Also, I think the issue was related only to Multi-axis crosshair cursors - i.e., crosshair cursors that span the whole viewport, not just one signal axes system. Multi-axis cursors are not (supposed to be) bound to the data boundaries, so it is possible to have the cursors go beyond these.

It may be a design flaw, worth re-thinking.

Cheers,

C.
